// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eke.proto

package fi.hsl.common.transitdata.proto;

public final class Eke {
  private Eke() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EkeSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.EkeSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 ekeDate = 1;</code>
     * @return Whether the ekeDate field is set.
     */
    boolean hasEkeDate();
    /**
     * <code>required int64 ekeDate = 1;</code>
     * @return The ekeDate.
     */
    long getEkeDate();

    /**
     * <code>required int32 trainNumber = 2;</code>
     * @return Whether the trainNumber field is set.
     */
    boolean hasTrainNumber();
    /**
     * <code>required int32 trainNumber = 2;</code>
     * @return The trainNumber.
     */
    int getTrainNumber();

    /**
     * <code>required string topicPart = 3;</code>
     * @return Whether the topicPart field is set.
     */
    boolean hasTopicPart();
    /**
     * <code>required string topicPart = 3;</code>
     * @return The topicPart.
     */
    java.lang.String getTopicPart();
    /**
     * <code>required string topicPart = 3;</code>
     * @return The bytes for topicPart.
     */
    com.google.protobuf.ByteString
        getTopicPartBytes();
  }
  /**
   * Protobuf type {@code proto.EkeSummary}
   */
  public static final class EkeSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.EkeSummary)
      EkeSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EkeSummary.newBuilder() to construct.
    private EkeSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EkeSummary() {
      topicPart_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EkeSummary();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fi.hsl.common.transitdata.proto.Eke.internal_static_proto_EkeSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fi.hsl.common.transitdata.proto.Eke.internal_static_proto_EkeSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fi.hsl.common.transitdata.proto.Eke.EkeSummary.class, fi.hsl.common.transitdata.proto.Eke.EkeSummary.Builder.class);
    }

    private int bitField0_;
    public static final int EKEDATE_FIELD_NUMBER = 1;
    private long ekeDate_ = 0L;
    /**
     * <code>required int64 ekeDate = 1;</code>
     * @return Whether the ekeDate field is set.
     */
    @java.lang.Override
    public boolean hasEkeDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 ekeDate = 1;</code>
     * @return The ekeDate.
     */
    @java.lang.Override
    public long getEkeDate() {
      return ekeDate_;
    }

    public static final int TRAINNUMBER_FIELD_NUMBER = 2;
    private int trainNumber_ = 0;
    /**
     * <code>required int32 trainNumber = 2;</code>
     * @return Whether the trainNumber field is set.
     */
    @java.lang.Override
    public boolean hasTrainNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 trainNumber = 2;</code>
     * @return The trainNumber.
     */
    @java.lang.Override
    public int getTrainNumber() {
      return trainNumber_;
    }

    public static final int TOPICPART_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object topicPart_ = "";
    /**
     * <code>required string topicPart = 3;</code>
     * @return Whether the topicPart field is set.
     */
    @java.lang.Override
    public boolean hasTopicPart() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string topicPart = 3;</code>
     * @return The topicPart.
     */
    @java.lang.Override
    public java.lang.String getTopicPart() {
      java.lang.Object ref = topicPart_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topicPart_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topicPart = 3;</code>
     * @return The bytes for topicPart.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicPartBytes() {
      java.lang.Object ref = topicPart_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicPart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEkeDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrainNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTopicPart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, ekeDate_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, trainNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topicPart_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, ekeDate_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, trainNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topicPart_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fi.hsl.common.transitdata.proto.Eke.EkeSummary)) {
        return super.equals(obj);
      }
      fi.hsl.common.transitdata.proto.Eke.EkeSummary other = (fi.hsl.common.transitdata.proto.Eke.EkeSummary) obj;

      if (hasEkeDate() != other.hasEkeDate()) return false;
      if (hasEkeDate()) {
        if (getEkeDate()
            != other.getEkeDate()) return false;
      }
      if (hasTrainNumber() != other.hasTrainNumber()) return false;
      if (hasTrainNumber()) {
        if (getTrainNumber()
            != other.getTrainNumber()) return false;
      }
      if (hasTopicPart() != other.hasTopicPart()) return false;
      if (hasTopicPart()) {
        if (!getTopicPart()
            .equals(other.getTopicPart())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEkeDate()) {
        hash = (37 * hash) + EKEDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEkeDate());
      }
      if (hasTrainNumber()) {
        hash = (37 * hash) + TRAINNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getTrainNumber();
      }
      if (hasTopicPart()) {
        hash = (37 * hash) + TOPICPART_FIELD_NUMBER;
        hash = (53 * hash) + getTopicPart().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fi.hsl.common.transitdata.proto.Eke.EkeSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.EkeSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.EkeSummary)
        fi.hsl.common.transitdata.proto.Eke.EkeSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fi.hsl.common.transitdata.proto.Eke.internal_static_proto_EkeSummary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fi.hsl.common.transitdata.proto.Eke.internal_static_proto_EkeSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fi.hsl.common.transitdata.proto.Eke.EkeSummary.class, fi.hsl.common.transitdata.proto.Eke.EkeSummary.Builder.class);
      }

      // Construct using fi.hsl.common.transitdata.proto.Eke.EkeSummary.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ekeDate_ = 0L;
        trainNumber_ = 0;
        topicPart_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fi.hsl.common.transitdata.proto.Eke.internal_static_proto_EkeSummary_descriptor;
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.Eke.EkeSummary getDefaultInstanceForType() {
        return fi.hsl.common.transitdata.proto.Eke.EkeSummary.getDefaultInstance();
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.Eke.EkeSummary build() {
        fi.hsl.common.transitdata.proto.Eke.EkeSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.Eke.EkeSummary buildPartial() {
        fi.hsl.common.transitdata.proto.Eke.EkeSummary result = new fi.hsl.common.transitdata.proto.Eke.EkeSummary(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fi.hsl.common.transitdata.proto.Eke.EkeSummary result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ekeDate_ = ekeDate_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.trainNumber_ = trainNumber_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.topicPart_ = topicPart_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fi.hsl.common.transitdata.proto.Eke.EkeSummary) {
          return mergeFrom((fi.hsl.common.transitdata.proto.Eke.EkeSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fi.hsl.common.transitdata.proto.Eke.EkeSummary other) {
        if (other == fi.hsl.common.transitdata.proto.Eke.EkeSummary.getDefaultInstance()) return this;
        if (other.hasEkeDate()) {
          setEkeDate(other.getEkeDate());
        }
        if (other.hasTrainNumber()) {
          setTrainNumber(other.getTrainNumber());
        }
        if (other.hasTopicPart()) {
          topicPart_ = other.topicPart_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasEkeDate()) {
          return false;
        }
        if (!hasTrainNumber()) {
          return false;
        }
        if (!hasTopicPart()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ekeDate_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                trainNumber_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                topicPart_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long ekeDate_ ;
      /**
       * <code>required int64 ekeDate = 1;</code>
       * @return Whether the ekeDate field is set.
       */
      @java.lang.Override
      public boolean hasEkeDate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 ekeDate = 1;</code>
       * @return The ekeDate.
       */
      @java.lang.Override
      public long getEkeDate() {
        return ekeDate_;
      }
      /**
       * <code>required int64 ekeDate = 1;</code>
       * @param value The ekeDate to set.
       * @return This builder for chaining.
       */
      public Builder setEkeDate(long value) {
        
        ekeDate_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ekeDate = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEkeDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ekeDate_ = 0L;
        onChanged();
        return this;
      }

      private int trainNumber_ ;
      /**
       * <code>required int32 trainNumber = 2;</code>
       * @return Whether the trainNumber field is set.
       */
      @java.lang.Override
      public boolean hasTrainNumber() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 trainNumber = 2;</code>
       * @return The trainNumber.
       */
      @java.lang.Override
      public int getTrainNumber() {
        return trainNumber_;
      }
      /**
       * <code>required int32 trainNumber = 2;</code>
       * @param value The trainNumber to set.
       * @return This builder for chaining.
       */
      public Builder setTrainNumber(int value) {
        
        trainNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 trainNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrainNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trainNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object topicPart_ = "";
      /**
       * <code>required string topicPart = 3;</code>
       * @return Whether the topicPart field is set.
       */
      public boolean hasTopicPart() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string topicPart = 3;</code>
       * @return The topicPart.
       */
      public java.lang.String getTopicPart() {
        java.lang.Object ref = topicPart_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topicPart_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string topicPart = 3;</code>
       * @return The bytes for topicPart.
       */
      public com.google.protobuf.ByteString
          getTopicPartBytes() {
        java.lang.Object ref = topicPart_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topicPart_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topicPart = 3;</code>
       * @param value The topicPart to set.
       * @return This builder for chaining.
       */
      public Builder setTopicPart(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        topicPart_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required string topicPart = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopicPart() {
        topicPart_ = getDefaultInstance().getTopicPart();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>required string topicPart = 3;</code>
       * @param value The bytes for topicPart to set.
       * @return This builder for chaining.
       */
      public Builder setTopicPartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        topicPart_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.EkeSummary)
    }

    // @@protoc_insertion_point(class_scope:proto.EkeSummary)
    private static final fi.hsl.common.transitdata.proto.Eke.EkeSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fi.hsl.common.transitdata.proto.Eke.EkeSummary();
    }

    public static fi.hsl.common.transitdata.proto.Eke.EkeSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EkeSummary>
        PARSER = new com.google.protobuf.AbstractParser<EkeSummary>() {
      @java.lang.Override
      public EkeSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EkeSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EkeSummary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fi.hsl.common.transitdata.proto.Eke.EkeSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EkeSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EkeSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\teke.proto\022\005proto\"E\n\nEkeSummary\022\017\n\007ekeD" +
      "ate\030\001 \002(\003\022\023\n\013trainNumber\030\002 \002(\005\022\021\n\ttopicP" +
      "art\030\003 \002(\tB&\n\037fi.hsl.common.transitdata.p" +
      "rotoB\003Eke"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_EkeSummary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_EkeSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EkeSummary_descriptor,
        new java.lang.String[] { "EkeDate", "TrainNumber", "TopicPart", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
