// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal-messages.proto

package fi.hsl.common.transitdata.proto;

public final class InternalMessages {
  private InternalMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TripCancellationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.TripCancellation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 SchemaVersion = 1 [default = 1];</code>
     */
    boolean hasSchemaVersion();
    /**
     * <code>required int32 SchemaVersion = 1 [default = 1];</code>
     */
    int getSchemaVersion();

    /**
     * <code>optional string trip_id = 2;</code>
     */
    boolean hasTripId();
    /**
     * <code>optional string trip_id = 2;</code>
     */
    java.lang.String getTripId();
    /**
     * <code>optional string trip_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getTripIdBytes();

    /**
     * <code>optional string route_id = 3;</code>
     */
    boolean hasRouteId();
    /**
     * <code>optional string route_id = 3;</code>
     */
    java.lang.String getRouteId();
    /**
     * <code>optional string route_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getRouteIdBytes();

    /**
     * <code>optional uint32 direction_id = 4;</code>
     */
    boolean hasDirectionId();
    /**
     * <code>optional uint32 direction_id = 4;</code>
     */
    int getDirectionId();

    /**
     * <code>optional string start_time = 5;</code>
     */
    boolean hasStartTime();
    /**
     * <code>optional string start_time = 5;</code>
     */
    java.lang.String getStartTime();
    /**
     * <code>optional string start_time = 5;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <code>optional string start_date = 6;</code>
     */
    boolean hasStartDate();
    /**
     * <code>optional string start_date = 6;</code>
     */
    java.lang.String getStartDate();
    /**
     * <code>optional string start_date = 6;</code>
     */
    com.google.protobuf.ByteString
        getStartDateBytes();

    /**
     * <code>required .proto.TripCancellation.Status status = 7;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .proto.TripCancellation.Status status = 7;</code>
     */
    fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status getStatus();
  }
  /**
   * Protobuf type {@code proto.TripCancellation}
   */
  public  static final class TripCancellation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.TripCancellation)
      TripCancellationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TripCancellation.newBuilder() to construct.
    private TripCancellation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TripCancellation() {
      schemaVersion_ = 1;
      tripId_ = "";
      routeId_ = "";
      directionId_ = 0;
      startTime_ = "";
      startDate_ = "";
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TripCancellation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              schemaVersion_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              tripId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              routeId_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              directionId_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              startTime_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              startDate_ = bs;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status value = fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                status_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fi.hsl.common.transitdata.proto.InternalMessages.internal_static_proto_TripCancellation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fi.hsl.common.transitdata.proto.InternalMessages.internal_static_proto_TripCancellation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.class, fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Builder.class);
    }

    /**
     * <pre>
     * This message is only used to either cancel a trip or mark a previously canceled trip as running as scheduled
     * </pre>
     *
     * Protobuf enum {@code proto.TripCancellation.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RUNNING = 0;</code>
       */
      RUNNING(0),
      /**
       * <code>CANCELED = 1;</code>
       */
      CANCELED(1),
      ;

      /**
       * <code>RUNNING = 0;</code>
       */
      public static final int RUNNING_VALUE = 0;
      /**
       * <code>CANCELED = 1;</code>
       */
      public static final int CANCELED_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return RUNNING;
          case 1: return CANCELED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.TripCancellation.Status)
    }

    private int bitField0_;
    public static final int SCHEMAVERSION_FIELD_NUMBER = 1;
    private int schemaVersion_;
    /**
     * <code>required int32 SchemaVersion = 1 [default = 1];</code>
     */
    public boolean hasSchemaVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 SchemaVersion = 1 [default = 1];</code>
     */
    public int getSchemaVersion() {
      return schemaVersion_;
    }

    public static final int TRIP_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object tripId_;
    /**
     * <code>optional string trip_id = 2;</code>
     */
    public boolean hasTripId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string trip_id = 2;</code>
     */
    public java.lang.String getTripId() {
      java.lang.Object ref = tripId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tripId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trip_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTripIdBytes() {
      java.lang.Object ref = tripId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tripId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTE_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object routeId_;
    /**
     * <code>optional string route_id = 3;</code>
     */
    public boolean hasRouteId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string route_id = 3;</code>
     */
    public java.lang.String getRouteId() {
      java.lang.Object ref = routeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          routeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string route_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRouteIdBytes() {
      java.lang.Object ref = routeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_ID_FIELD_NUMBER = 4;
    private int directionId_;
    /**
     * <code>optional uint32 direction_id = 4;</code>
     */
    public boolean hasDirectionId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 direction_id = 4;</code>
     */
    public int getDirectionId() {
      return directionId_;
    }

    public static final int START_TIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object startTime_;
    /**
     * <code>optional string start_time = 5;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string start_time = 5;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string start_time = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_DATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object startDate_;
    /**
     * <code>optional string start_date = 6;</code>
     */
    public boolean hasStartDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string start_date = 6;</code>
     */
    public java.lang.String getStartDate() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string start_date = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStartDateBytes() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    private int status_;
    /**
     * <code>required .proto.TripCancellation.Status status = 7;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .proto.TripCancellation.Status status = 7;</code>
     */
    public fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status getStatus() {
      @SuppressWarnings("deprecation")
      fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status result = fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status.valueOf(status_);
      return result == null ? fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status.RUNNING : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSchemaVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, schemaVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tripId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, routeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, directionId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, startTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, startDate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, schemaVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tripId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, routeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, directionId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, startTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, startDate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation)) {
        return super.equals(obj);
      }
      fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation other = (fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation) obj;

      boolean result = true;
      result = result && (hasSchemaVersion() == other.hasSchemaVersion());
      if (hasSchemaVersion()) {
        result = result && (getSchemaVersion()
            == other.getSchemaVersion());
      }
      result = result && (hasTripId() == other.hasTripId());
      if (hasTripId()) {
        result = result && getTripId()
            .equals(other.getTripId());
      }
      result = result && (hasRouteId() == other.hasRouteId());
      if (hasRouteId()) {
        result = result && getRouteId()
            .equals(other.getRouteId());
      }
      result = result && (hasDirectionId() == other.hasDirectionId());
      if (hasDirectionId()) {
        result = result && (getDirectionId()
            == other.getDirectionId());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && getStartTime()
            .equals(other.getStartTime());
      }
      result = result && (hasStartDate() == other.hasStartDate());
      if (hasStartDate()) {
        result = result && getStartDate()
            .equals(other.getStartDate());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && status_ == other.status_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSchemaVersion()) {
        hash = (37 * hash) + SCHEMAVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getSchemaVersion();
      }
      if (hasTripId()) {
        hash = (37 * hash) + TRIP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTripId().hashCode();
      }
      if (hasRouteId()) {
        hash = (37 * hash) + ROUTE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getRouteId().hashCode();
      }
      if (hasDirectionId()) {
        hash = (37 * hash) + DIRECTION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDirectionId();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + START_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime().hashCode();
      }
      if (hasStartDate()) {
        hash = (37 * hash) + START_DATE_FIELD_NUMBER;
        hash = (53 * hash) + getStartDate().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.TripCancellation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.TripCancellation)
        fi.hsl.common.transitdata.proto.InternalMessages.TripCancellationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fi.hsl.common.transitdata.proto.InternalMessages.internal_static_proto_TripCancellation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fi.hsl.common.transitdata.proto.InternalMessages.internal_static_proto_TripCancellation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.class, fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Builder.class);
      }

      // Construct using fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaVersion_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        tripId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        routeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        directionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        startDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fi.hsl.common.transitdata.proto.InternalMessages.internal_static_proto_TripCancellation_descriptor;
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation getDefaultInstanceForType() {
        return fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.getDefaultInstance();
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation build() {
        fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation buildPartial() {
        fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation result = new fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.schemaVersion_ = schemaVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tripId_ = tripId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.routeId_ = routeId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.directionId_ = directionId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.startDate_ = startDate_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation) {
          return mergeFrom((fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation other) {
        if (other == fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.getDefaultInstance()) return this;
        if (other.hasSchemaVersion()) {
          setSchemaVersion(other.getSchemaVersion());
        }
        if (other.hasTripId()) {
          bitField0_ |= 0x00000002;
          tripId_ = other.tripId_;
          onChanged();
        }
        if (other.hasRouteId()) {
          bitField0_ |= 0x00000004;
          routeId_ = other.routeId_;
          onChanged();
        }
        if (other.hasDirectionId()) {
          setDirectionId(other.getDirectionId());
        }
        if (other.hasStartTime()) {
          bitField0_ |= 0x00000010;
          startTime_ = other.startTime_;
          onChanged();
        }
        if (other.hasStartDate()) {
          bitField0_ |= 0x00000020;
          startDate_ = other.startDate_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSchemaVersion()) {
          return false;
        }
        if (!hasStatus()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int schemaVersion_ = 1;
      /**
       * <code>required int32 SchemaVersion = 1 [default = 1];</code>
       */
      public boolean hasSchemaVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 SchemaVersion = 1 [default = 1];</code>
       */
      public int getSchemaVersion() {
        return schemaVersion_;
      }
      /**
       * <code>required int32 SchemaVersion = 1 [default = 1];</code>
       */
      public Builder setSchemaVersion(int value) {
        bitField0_ |= 0x00000001;
        schemaVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 SchemaVersion = 1 [default = 1];</code>
       */
      public Builder clearSchemaVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        schemaVersion_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object tripId_ = "";
      /**
       * <code>optional string trip_id = 2;</code>
       */
      public boolean hasTripId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string trip_id = 2;</code>
       */
      public java.lang.String getTripId() {
        java.lang.Object ref = tripId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tripId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trip_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTripIdBytes() {
        java.lang.Object ref = tripId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tripId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trip_id = 2;</code>
       */
      public Builder setTripId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tripId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trip_id = 2;</code>
       */
      public Builder clearTripId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tripId_ = getDefaultInstance().getTripId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trip_id = 2;</code>
       */
      public Builder setTripIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tripId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object routeId_ = "";
      /**
       * <code>optional string route_id = 3;</code>
       */
      public boolean hasRouteId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string route_id = 3;</code>
       */
      public java.lang.String getRouteId() {
        java.lang.Object ref = routeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            routeId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string route_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRouteIdBytes() {
        java.lang.Object ref = routeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string route_id = 3;</code>
       */
      public Builder setRouteId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        routeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string route_id = 3;</code>
       */
      public Builder clearRouteId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        routeId_ = getDefaultInstance().getRouteId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string route_id = 3;</code>
       */
      public Builder setRouteIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        routeId_ = value;
        onChanged();
        return this;
      }

      private int directionId_ ;
      /**
       * <code>optional uint32 direction_id = 4;</code>
       */
      public boolean hasDirectionId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 direction_id = 4;</code>
       */
      public int getDirectionId() {
        return directionId_;
      }
      /**
       * <code>optional uint32 direction_id = 4;</code>
       */
      public Builder setDirectionId(int value) {
        bitField0_ |= 0x00000008;
        directionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 direction_id = 4;</code>
       */
      public Builder clearDirectionId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        directionId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object startTime_ = "";
      /**
       * <code>optional string start_time = 5;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string start_time = 5;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            startTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string start_time = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string start_time = 5;</code>
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string start_time = 5;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string start_time = 5;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        startTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startDate_ = "";
      /**
       * <code>optional string start_date = 6;</code>
       */
      public boolean hasStartDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string start_date = 6;</code>
       */
      public java.lang.String getStartDate() {
        java.lang.Object ref = startDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            startDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string start_date = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStartDateBytes() {
        java.lang.Object ref = startDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string start_date = 6;</code>
       */
      public Builder setStartDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        startDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string start_date = 6;</code>
       */
      public Builder clearStartDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        startDate_ = getDefaultInstance().getStartDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string start_date = 6;</code>
       */
      public Builder setStartDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        startDate_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>required .proto.TripCancellation.Status status = 7;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required .proto.TripCancellation.Status status = 7;</code>
       */
      public fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status getStatus() {
        @SuppressWarnings("deprecation")
        fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status result = fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status.valueOf(status_);
        return result == null ? fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status.RUNNING : result;
      }
      /**
       * <code>required .proto.TripCancellation.Status status = 7;</code>
       */
      public Builder setStatus(fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.TripCancellation.Status status = 7;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.TripCancellation)
    }

    // @@protoc_insertion_point(class_scope:proto.TripCancellation)
    private static final fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation();
    }

    public static fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TripCancellation>
        PARSER = new com.google.protobuf.AbstractParser<TripCancellation>() {
      @java.lang.Override
      public TripCancellation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TripCancellation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TripCancellation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TripCancellation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fi.hsl.common.transitdata.proto.InternalMessages.TripCancellation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TripCancellation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TripCancellation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027internal-messages.proto\022\005proto\"\342\001\n\020Tri" +
      "pCancellation\022\030\n\rSchemaVersion\030\001 \002(\005:\0011\022" +
      "\017\n\007trip_id\030\002 \001(\t\022\020\n\010route_id\030\003 \001(\t\022\024\n\014di" +
      "rection_id\030\004 \001(\r\022\022\n\nstart_time\030\005 \001(\t\022\022\n\n" +
      "start_date\030\006 \001(\t\022.\n\006status\030\007 \002(\0162\036.proto" +
      ".TripCancellation.Status\"#\n\006Status\022\013\n\007RU" +
      "NNING\020\000\022\014\n\010CANCELED\020\001B3\n\037fi.hsl.common.t" +
      "ransitdata.protoB\020InternalMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_TripCancellation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_TripCancellation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TripCancellation_descriptor,
        new java.lang.String[] { "SchemaVersion", "TripId", "RouteId", "DirectionId", "StartTime", "StartDate", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
