// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pulsar-messages.proto

package fi.hsl.common.transitdata.proto;

public final class PulsarMessageProtos {
  private PulsarMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StopEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.StopEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 dated_vehicle_journey_id = 1;</code>
     */
    boolean hasDatedVehicleJourneyId();
    /**
     * <code>required int64 dated_vehicle_journey_id = 1;</code>
     */
    long getDatedVehicleJourneyId();

    /**
     * <code>required .proto.StopEvent.EventType event_type = 2;</code>
     */
    boolean hasEventType();
    /**
     * <code>required .proto.StopEvent.EventType event_type = 2;</code>
     */
    fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType getEventType();

    /**
     * <code>required int64 target_time = 3;</code>
     */
    boolean hasTargetTime();
    /**
     * <code>required int64 target_time = 3;</code>
     */
    long getTargetTime();

    /**
     * <code>required int32 stop_id = 4;</code>
     */
    boolean hasStopId();
    /**
     * <code>required int32 stop_id = 4;</code>
     */
    int getStopId();

    /**
     * <code>required int32 stop_seq = 5;</code>
     */
    boolean hasStopSeq();
    /**
     * <code>required int32 stop_seq = 5;</code>
     */
    int getStopSeq();

    /**
     * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
     */
    boolean hasScheduleRelationship();
    /**
     * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
     */
    fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship getScheduleRelationship();
  }
  /**
   * Protobuf type {@code proto.StopEvent}
   */
  public  static final class StopEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.StopEvent)
      StopEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StopEvent.newBuilder() to construct.
    private StopEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopEvent() {
      datedVehicleJourneyId_ = 0L;
      eventType_ = 0;
      targetTime_ = 0L;
      stopId_ = 0;
      stopSeq_ = 0;
      scheduleRelationship_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StopEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              datedVehicleJourneyId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType value = fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                eventType_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              targetTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              stopId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              stopSeq_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship value = fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                scheduleRelationship_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fi.hsl.common.transitdata.proto.PulsarMessageProtos.internal_static_proto_StopEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fi.hsl.common.transitdata.proto.PulsarMessageProtos.internal_static_proto_StopEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.class, fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.StopEvent.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ARRIVAL = 0;</code>
       */
      ARRIVAL(0),
      /**
       * <code>DEPARTURE = 1;</code>
       */
      DEPARTURE(1),
      ;

      /**
       * <code>ARRIVAL = 0;</code>
       */
      public static final int ARRIVAL_VALUE = 0;
      /**
       * <code>DEPARTURE = 1;</code>
       */
      public static final int DEPARTURE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventType valueOf(int value) {
        return forNumber(value);
      }

      public static EventType forNumber(int value) {
        switch (value) {
          case 0: return ARRIVAL;
          case 1: return DEPARTURE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EventType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EventType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.StopEvent.EventType)
    }

    /**
     * Protobuf enum {@code proto.StopEvent.ScheduleRelationship}
     */
    public enum ScheduleRelationship
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SCHEDULED = 0;</code>
       */
      SCHEDULED(0),
      /**
       * <code>SKIPPED = 1;</code>
       */
      SKIPPED(1),
      ;

      /**
       * <code>SCHEDULED = 0;</code>
       */
      public static final int SCHEDULED_VALUE = 0;
      /**
       * <code>SKIPPED = 1;</code>
       */
      public static final int SKIPPED_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ScheduleRelationship valueOf(int value) {
        return forNumber(value);
      }

      public static ScheduleRelationship forNumber(int value) {
        switch (value) {
          case 0: return SCHEDULED;
          case 1: return SKIPPED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ScheduleRelationship>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ScheduleRelationship> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ScheduleRelationship>() {
              public ScheduleRelationship findValueByNumber(int number) {
                return ScheduleRelationship.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.getDescriptor().getEnumTypes().get(1);
      }

      private static final ScheduleRelationship[] VALUES = values();

      public static ScheduleRelationship valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ScheduleRelationship(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.StopEvent.ScheduleRelationship)
    }

    private int bitField0_;
    public static final int DATED_VEHICLE_JOURNEY_ID_FIELD_NUMBER = 1;
    private long datedVehicleJourneyId_;
    /**
     * <code>required int64 dated_vehicle_journey_id = 1;</code>
     */
    public boolean hasDatedVehicleJourneyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 dated_vehicle_journey_id = 1;</code>
     */
    public long getDatedVehicleJourneyId() {
      return datedVehicleJourneyId_;
    }

    public static final int EVENT_TYPE_FIELD_NUMBER = 2;
    private int eventType_;
    /**
     * <code>required .proto.StopEvent.EventType event_type = 2;</code>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .proto.StopEvent.EventType event_type = 2;</code>
     */
    public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType getEventType() {
      @SuppressWarnings("deprecation")
      fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType result = fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType.valueOf(eventType_);
      return result == null ? fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType.ARRIVAL : result;
    }

    public static final int TARGET_TIME_FIELD_NUMBER = 3;
    private long targetTime_;
    /**
     * <code>required int64 target_time = 3;</code>
     */
    public boolean hasTargetTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 target_time = 3;</code>
     */
    public long getTargetTime() {
      return targetTime_;
    }

    public static final int STOP_ID_FIELD_NUMBER = 4;
    private int stopId_;
    /**
     * <code>required int32 stop_id = 4;</code>
     */
    public boolean hasStopId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 stop_id = 4;</code>
     */
    public int getStopId() {
      return stopId_;
    }

    public static final int STOP_SEQ_FIELD_NUMBER = 5;
    private int stopSeq_;
    /**
     * <code>required int32 stop_seq = 5;</code>
     */
    public boolean hasStopSeq() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 stop_seq = 5;</code>
     */
    public int getStopSeq() {
      return stopSeq_;
    }

    public static final int SCHEDULE_RELATIONSHIP_FIELD_NUMBER = 6;
    private int scheduleRelationship_;
    /**
     * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
     */
    public boolean hasScheduleRelationship() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
     */
    public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship getScheduleRelationship() {
      @SuppressWarnings("deprecation")
      fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship result = fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship.valueOf(scheduleRelationship_);
      return result == null ? fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship.SCHEDULED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDatedVehicleJourneyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStopId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStopSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScheduleRelationship()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, datedVehicleJourneyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, eventType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, targetTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, stopId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, stopSeq_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, scheduleRelationship_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, datedVehicleJourneyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, eventType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, targetTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, stopId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, stopSeq_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, scheduleRelationship_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent)) {
        return super.equals(obj);
      }
      fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent other = (fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent) obj;

      boolean result = true;
      result = result && (hasDatedVehicleJourneyId() == other.hasDatedVehicleJourneyId());
      if (hasDatedVehicleJourneyId()) {
        result = result && (getDatedVehicleJourneyId()
            == other.getDatedVehicleJourneyId());
      }
      result = result && (hasEventType() == other.hasEventType());
      if (hasEventType()) {
        result = result && eventType_ == other.eventType_;
      }
      result = result && (hasTargetTime() == other.hasTargetTime());
      if (hasTargetTime()) {
        result = result && (getTargetTime()
            == other.getTargetTime());
      }
      result = result && (hasStopId() == other.hasStopId());
      if (hasStopId()) {
        result = result && (getStopId()
            == other.getStopId());
      }
      result = result && (hasStopSeq() == other.hasStopSeq());
      if (hasStopSeq()) {
        result = result && (getStopSeq()
            == other.getStopSeq());
      }
      result = result && (hasScheduleRelationship() == other.hasScheduleRelationship());
      if (hasScheduleRelationship()) {
        result = result && scheduleRelationship_ == other.scheduleRelationship_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDatedVehicleJourneyId()) {
        hash = (37 * hash) + DATED_VEHICLE_JOURNEY_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDatedVehicleJourneyId());
      }
      if (hasEventType()) {
        hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + eventType_;
      }
      if (hasTargetTime()) {
        hash = (37 * hash) + TARGET_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTargetTime());
      }
      if (hasStopId()) {
        hash = (37 * hash) + STOP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getStopId();
      }
      if (hasStopSeq()) {
        hash = (37 * hash) + STOP_SEQ_FIELD_NUMBER;
        hash = (53 * hash) + getStopSeq();
      }
      if (hasScheduleRelationship()) {
        hash = (37 * hash) + SCHEDULE_RELATIONSHIP_FIELD_NUMBER;
        hash = (53 * hash) + scheduleRelationship_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.StopEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.StopEvent)
        fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fi.hsl.common.transitdata.proto.PulsarMessageProtos.internal_static_proto_StopEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fi.hsl.common.transitdata.proto.PulsarMessageProtos.internal_static_proto_StopEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.class, fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.Builder.class);
      }

      // Construct using fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        datedVehicleJourneyId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        targetTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        stopId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        stopSeq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        scheduleRelationship_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fi.hsl.common.transitdata.proto.PulsarMessageProtos.internal_static_proto_StopEvent_descriptor;
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent getDefaultInstanceForType() {
        return fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.getDefaultInstance();
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent build() {
        fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent buildPartial() {
        fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent result = new fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.datedVehicleJourneyId_ = datedVehicleJourneyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.targetTime_ = targetTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.stopId_ = stopId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.stopSeq_ = stopSeq_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.scheduleRelationship_ = scheduleRelationship_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent) {
          return mergeFrom((fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent other) {
        if (other == fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.getDefaultInstance()) return this;
        if (other.hasDatedVehicleJourneyId()) {
          setDatedVehicleJourneyId(other.getDatedVehicleJourneyId());
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasTargetTime()) {
          setTargetTime(other.getTargetTime());
        }
        if (other.hasStopId()) {
          setStopId(other.getStopId());
        }
        if (other.hasStopSeq()) {
          setStopSeq(other.getStopSeq());
        }
        if (other.hasScheduleRelationship()) {
          setScheduleRelationship(other.getScheduleRelationship());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDatedVehicleJourneyId()) {
          return false;
        }
        if (!hasEventType()) {
          return false;
        }
        if (!hasTargetTime()) {
          return false;
        }
        if (!hasStopId()) {
          return false;
        }
        if (!hasStopSeq()) {
          return false;
        }
        if (!hasScheduleRelationship()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long datedVehicleJourneyId_ ;
      /**
       * <code>required int64 dated_vehicle_journey_id = 1;</code>
       */
      public boolean hasDatedVehicleJourneyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 dated_vehicle_journey_id = 1;</code>
       */
      public long getDatedVehicleJourneyId() {
        return datedVehicleJourneyId_;
      }
      /**
       * <code>required int64 dated_vehicle_journey_id = 1;</code>
       */
      public Builder setDatedVehicleJourneyId(long value) {
        bitField0_ |= 0x00000001;
        datedVehicleJourneyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 dated_vehicle_journey_id = 1;</code>
       */
      public Builder clearDatedVehicleJourneyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        datedVehicleJourneyId_ = 0L;
        onChanged();
        return this;
      }

      private int eventType_ = 0;
      /**
       * <code>required .proto.StopEvent.EventType event_type = 2;</code>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .proto.StopEvent.EventType event_type = 2;</code>
       */
      public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType getEventType() {
        @SuppressWarnings("deprecation")
        fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType result = fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType.valueOf(eventType_);
        return result == null ? fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType.ARRIVAL : result;
      }
      /**
       * <code>required .proto.StopEvent.EventType event_type = 2;</code>
       */
      public Builder setEventType(fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        eventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.StopEvent.EventType event_type = 2;</code>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        eventType_ = 0;
        onChanged();
        return this;
      }

      private long targetTime_ ;
      /**
       * <code>required int64 target_time = 3;</code>
       */
      public boolean hasTargetTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 target_time = 3;</code>
       */
      public long getTargetTime() {
        return targetTime_;
      }
      /**
       * <code>required int64 target_time = 3;</code>
       */
      public Builder setTargetTime(long value) {
        bitField0_ |= 0x00000004;
        targetTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 target_time = 3;</code>
       */
      public Builder clearTargetTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetTime_ = 0L;
        onChanged();
        return this;
      }

      private int stopId_ ;
      /**
       * <code>required int32 stop_id = 4;</code>
       */
      public boolean hasStopId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 stop_id = 4;</code>
       */
      public int getStopId() {
        return stopId_;
      }
      /**
       * <code>required int32 stop_id = 4;</code>
       */
      public Builder setStopId(int value) {
        bitField0_ |= 0x00000008;
        stopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stop_id = 4;</code>
       */
      public Builder clearStopId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        stopId_ = 0;
        onChanged();
        return this;
      }

      private int stopSeq_ ;
      /**
       * <code>required int32 stop_seq = 5;</code>
       */
      public boolean hasStopSeq() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 stop_seq = 5;</code>
       */
      public int getStopSeq() {
        return stopSeq_;
      }
      /**
       * <code>required int32 stop_seq = 5;</code>
       */
      public Builder setStopSeq(int value) {
        bitField0_ |= 0x00000010;
        stopSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stop_seq = 5;</code>
       */
      public Builder clearStopSeq() {
        bitField0_ = (bitField0_ & ~0x00000010);
        stopSeq_ = 0;
        onChanged();
        return this;
      }

      private int scheduleRelationship_ = 0;
      /**
       * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
       */
      public boolean hasScheduleRelationship() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
       */
      public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship getScheduleRelationship() {
        @SuppressWarnings("deprecation")
        fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship result = fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship.valueOf(scheduleRelationship_);
        return result == null ? fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship.SCHEDULED : result;
      }
      /**
       * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
       */
      public Builder setScheduleRelationship(fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent.ScheduleRelationship value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        scheduleRelationship_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.StopEvent.ScheduleRelationship schedule_relationship = 6;</code>
       */
      public Builder clearScheduleRelationship() {
        bitField0_ = (bitField0_ & ~0x00000020);
        scheduleRelationship_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.StopEvent)
    }

    // @@protoc_insertion_point(class_scope:proto.StopEvent)
    private static final fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent();
    }

    public static fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StopEvent>
        PARSER = new com.google.protobuf.AbstractParser<StopEvent>() {
      @java.lang.Override
      public StopEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fi.hsl.common.transitdata.proto.PulsarMessageProtos.StopEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StopEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StopEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025pulsar-messages.proto\022\005proto\"\270\002\n\tStopE" +
      "vent\022 \n\030dated_vehicle_journey_id\030\001 \002(\003\022." +
      "\n\nevent_type\030\002 \002(\0162\032.proto.StopEvent.Eve" +
      "ntType\022\023\n\013target_time\030\003 \002(\003\022\017\n\007stop_id\030\004" +
      " \002(\005\022\020\n\010stop_seq\030\005 \002(\005\022D\n\025schedule_relat" +
      "ionship\030\006 \002(\0162%.proto.StopEvent.Schedule" +
      "Relationship\"\'\n\tEventType\022\013\n\007ARRIVAL\020\000\022\r" +
      "\n\tDEPARTURE\020\001\"2\n\024ScheduleRelationship\022\r\n" +
      "\tSCHEDULED\020\000\022\013\n\007SKIPPED\020\001B6\n\037fi.hsl.comm" +
      "on.transitdata.protoB\023PulsarMessageProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_StopEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_StopEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StopEvent_descriptor,
        new java.lang.String[] { "DatedVehicleJourneyId", "EventType", "TargetTime", "StopId", "StopSeq", "ScheduleRelationship", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
