language: java
jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml-xpath-perl

cache:
  directories:
    - $HOME/.m2

script:
  - mvn test
  - mvn clean package
  - ls -la target/

deploy:
  - provider: script
    script: bash -c './prepare-bintray.sh'
    skip_cleanup: true
    on:
      branch: master
  - provider: bintray
    file: "./travis-bintray-deploy.json"
    user: "${BINTRAY_USER}"
    key: "${BINTRAY_KEY}"
    skip_cleanup: true
    on:
      branch: master
