sudo: required

services:
  - docker

language: java
jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml-xpath-perl

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn clean package --quiet -Dskip.unit.tests=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn surefire:test
  - mvn failsafe:integration-test
  - mvn failsafe:verify
  - ls -la target/

deploy:
  - provider: script
    script: bash -c './prepare-bintray.sh'
    skip_cleanup: true
    on:
      branch: master
  - provider: bintray
    file: "./travis-bintray-deploy.json"
    user: "${BINTRAY_USER}"
    key: "${BINTRAY_KEY}"
    skip_cleanup: true
    on:
      branch: master
