language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn test
  - mvn clean package
  - ls -la target/

deploy:
  - provider: script
    script: bash -c './prepare-bintray.sh'
    skip_cleanup: true
    on:
      all_branches: true
  - provider: bintray
    file: "./travis-bintray-deploy.json"
    user: "${BINTRAY_USER}"
    key: "${BINTRAY_KEY}"
    skip_cleanup: true
    on:
      # FIXME: Comment out until upload is sorted out.
      #tags: true
      all_branches: true
      #branch: master
  - provider: script
    script: bash -c 'ls -la target/'
    skip_cleanup: true
    on:
      all_branches: true
