sudo: required

services:
  - docker

language: java
jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml-xpath-perl

cache:
  directories:
    - $HOME/.m2

before_install:
  - mvn install --quiet -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test
  - mvn verify -P integration-test
  - mvn --quiet clean package
  - ls -la target/

deploy:
  - provider: script
    script: bash -c './prepare-bintray.sh'
    skip_cleanup: true
    on:
      branch: test-deploy
  - provider: bintray
    file: "./travis-bintray-deploy.json"
    user: "${BINTRAY_USER}"
    key: "${BINTRAY_KEY}"
    skip_cleanup: true
    on:
      branch: test-deploy
