language: java
jdk:
  - openjdk10

script:
  - mvn test
  - mvn clean package

deploy:
  - provider: bintray
    file: "./travis-bintray-deploy.json"
    user: "${BINTRAY_USER}"
    key: "${BINTRAY_KEY}"
    skip_cleanup: true
    on:
      # FIXME: Comment out until upload is sorted out.
      #tags: true
      #all_branches: true
      branch: master
