// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime-extension.proto

package fi.hsl.common.gtfsrt.proto;

public final class AlternativeStops {
  private AlternativeStops() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(fi.hsl.common.gtfsrt.proto.AlternativeStops.alternativeStopIds);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int ALTERNATIVE_STOP_IDS_FIELD_NUMBER = 1999;
  /**
   * <code>extend .transit_realtime.TripUpdate.StopTimeUpdate { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.TripUpdate.StopTimeUpdate,
      java.util.List<java.lang.String>> alternativeStopIds = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035gtfs-realtime-extension.proto\022\005proto\032\023" +
      "gtfs-realtime.proto:J\n\024alternative_stop_" +
      "ids\022+.transit_realtime.TripUpdate.StopTi" +
      "meUpdate\030\317\017 \003(\tB.\n\032fi.hsl.common.gtfsrt." +
      "protoB\020AlternativeStopsP\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.transit.realtime.GtfsRealtime.getDescriptor(),
        });
    alternativeStopIds.internalInit(descriptor.getExtensions().get(0));
    com.google.transit.realtime.GtfsRealtime.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
