// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mqtt.proto

package fi.hsl.common.mqtt.proto;

public final class Mqtt {
    private Mqtt() {
    }
    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface RawMessageOrBuilder
            extends
                // @@protoc_insertion_point(interface_extends:proto.RawMessage)
                com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 SchemaVersion = 1 [default = 1];</code>
         * @return Whether the schemaVersion field is set.
         */
        boolean hasSchemaVersion();
        /**
         * <code>required int32 SchemaVersion = 1 [default = 1];</code>
         * @return The schemaVersion.
         */
        int getSchemaVersion();

        /**
         * <code>optional string topic = 2;</code>
         * @return Whether the topic field is set.
         */
        boolean hasTopic();
        /**
         * <code>optional string topic = 2;</code>
         * @return The topic.
         */
        java.lang.String getTopic();
        /**
         * <code>optional string topic = 2;</code>
         * @return The bytes for topic.
         */
        com.google.protobuf.ByteString getTopicBytes();

        /**
         * <code>optional bytes payload = 3;</code>
         * @return Whether the payload field is set.
         */
        boolean hasPayload();
        /**
         * <code>optional bytes payload = 3;</code>
         * @return The payload.
         */
        com.google.protobuf.ByteString getPayload();
    }
    /**
     * Protobuf type {@code proto.RawMessage}
     */
    public static final class RawMessage extends com.google.protobuf.GeneratedMessageV3
            implements
                // @@protoc_insertion_point(message_implements:proto.RawMessage)
                RawMessageOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use RawMessage.newBuilder() to construct.
        private RawMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private RawMessage() {
            schemaVersion_ = 1;
            topic_ = "";
            payload_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new RawMessage();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return fi.hsl.common.mqtt.proto.Mqtt.internal_static_proto_RawMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return fi.hsl.common.mqtt.proto.Mqtt.internal_static_proto_RawMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(fi.hsl.common.mqtt.proto.Mqtt.RawMessage.class,
                            fi.hsl.common.mqtt.proto.Mqtt.RawMessage.Builder.class);
        }

        private int bitField0_;
        public static final int SCHEMAVERSION_FIELD_NUMBER = 1;
        private int schemaVersion_ = 1;
        /**
         * <code>required int32 SchemaVersion = 1 [default = 1];</code>
         * @return Whether the schemaVersion field is set.
         */
        @java.lang.Override
        public boolean hasSchemaVersion() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required int32 SchemaVersion = 1 [default = 1];</code>
         * @return The schemaVersion.
         */
        @java.lang.Override
        public int getSchemaVersion() {
            return schemaVersion_;
        }

        public static final int TOPIC_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object topic_ = "";
        /**
         * <code>optional string topic = 2;</code>
         * @return Whether the topic field is set.
         */
        @java.lang.Override
        public boolean hasTopic() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional string topic = 2;</code>
         * @return The topic.
         */
        @java.lang.Override
        public java.lang.String getTopic() {
            java.lang.Object ref = topic_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    topic_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string topic = 2;</code>
         * @return The bytes for topic.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getTopicBytes() {
            java.lang.Object ref = topic_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                topic_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PAYLOAD_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes payload = 3;</code>
         * @return Whether the payload field is set.
         */
        @java.lang.Override
        public boolean hasPayload() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional bytes payload = 3;</code>
         * @return The payload.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getPayload() {
            return payload_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasSchemaVersion()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeInt32(1, schemaVersion_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeBytes(3, payload_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, schemaVersion_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, payload_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof fi.hsl.common.mqtt.proto.Mqtt.RawMessage)) {
                return super.equals(obj);
            }
            fi.hsl.common.mqtt.proto.Mqtt.RawMessage other = (fi.hsl.common.mqtt.proto.Mqtt.RawMessage) obj;

            if (hasSchemaVersion() != other.hasSchemaVersion())
                return false;
            if (hasSchemaVersion()) {
                if (getSchemaVersion() != other.getSchemaVersion())
                    return false;
            }
            if (hasTopic() != other.hasTopic())
                return false;
            if (hasTopic()) {
                if (!getTopic().equals(other.getTopic()))
                    return false;
            }
            if (hasPayload() != other.hasPayload())
                return false;
            if (hasPayload()) {
                if (!getPayload().equals(other.getPayload()))
                    return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasSchemaVersion()) {
                hash = (37 * hash) + SCHEMAVERSION_FIELD_NUMBER;
                hash = (53 * hash) + getSchemaVersion();
            }
            if (hasTopic()) {
                hash = (37 * hash) + TOPIC_FIELD_NUMBER;
                hash = (53 * hash) + getTopic().hashCode();
            }
            if (hasPayload()) {
                hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
                hash = (53 * hash) + getPayload().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                    extensionRegistry);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }
        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(fi.hsl.common.mqtt.proto.Mqtt.RawMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code proto.RawMessage}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                implements
                    // @@protoc_insertion_point(builder_implements:proto.RawMessage)
                    fi.hsl.common.mqtt.proto.Mqtt.RawMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return fi.hsl.common.mqtt.proto.Mqtt.internal_static_proto_RawMessage_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return fi.hsl.common.mqtt.proto.Mqtt.internal_static_proto_RawMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(fi.hsl.common.mqtt.proto.Mqtt.RawMessage.class,
                                fi.hsl.common.mqtt.proto.Mqtt.RawMessage.Builder.class);
            }

            // Construct using fi.hsl.common.mqtt.proto.Mqtt.RawMessage.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                schemaVersion_ = 1;
                topic_ = "";
                payload_ = com.google.protobuf.ByteString.EMPTY;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return fi.hsl.common.mqtt.proto.Mqtt.internal_static_proto_RawMessage_descriptor;
            }

            @java.lang.Override
            public fi.hsl.common.mqtt.proto.Mqtt.RawMessage getDefaultInstanceForType() {
                return fi.hsl.common.mqtt.proto.Mqtt.RawMessage.getDefaultInstance();
            }

            @java.lang.Override
            public fi.hsl.common.mqtt.proto.Mqtt.RawMessage build() {
                fi.hsl.common.mqtt.proto.Mqtt.RawMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public fi.hsl.common.mqtt.proto.Mqtt.RawMessage buildPartial() {
                fi.hsl.common.mqtt.proto.Mqtt.RawMessage result = new fi.hsl.common.mqtt.proto.Mqtt.RawMessage(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(fi.hsl.common.mqtt.proto.Mqtt.RawMessage result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.schemaVersion_ = schemaVersion_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.topic_ = topic_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.payload_ = payload_;
                    to_bitField0_ |= 0x00000004;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                    java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof fi.hsl.common.mqtt.proto.Mqtt.RawMessage) {
                    return mergeFrom((fi.hsl.common.mqtt.proto.Mqtt.RawMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(fi.hsl.common.mqtt.proto.Mqtt.RawMessage other) {
                if (other == fi.hsl.common.mqtt.proto.Mqtt.RawMessage.getDefaultInstance())
                    return this;
                if (other.hasSchemaVersion()) {
                    setSchemaVersion(other.getSchemaVersion());
                }
                if (other.hasTopic()) {
                    topic_ = other.topic_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (other.hasPayload()) {
                    setPayload(other.getPayload());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasSchemaVersion()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0 :
                                done = true;
                                break;
                            case 8 : {
                                schemaVersion_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18 : {
                                topic_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26 : {
                                payload_ = input.readBytes();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            default : {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }
            private int bitField0_;

            private int schemaVersion_ = 1;
            /**
             * <code>required int32 SchemaVersion = 1 [default = 1];</code>
             * @return Whether the schemaVersion field is set.
             */
            @java.lang.Override
            public boolean hasSchemaVersion() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>required int32 SchemaVersion = 1 [default = 1];</code>
             * @return The schemaVersion.
             */
            @java.lang.Override
            public int getSchemaVersion() {
                return schemaVersion_;
            }
            /**
             * <code>required int32 SchemaVersion = 1 [default = 1];</code>
             * @param value The schemaVersion to set.
             * @return This builder for chaining.
             */
            public Builder setSchemaVersion(int value) {

                schemaVersion_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>required int32 SchemaVersion = 1 [default = 1];</code>
             * @return This builder for chaining.
             */
            public Builder clearSchemaVersion() {
                bitField0_ = (bitField0_ & ~0x00000001);
                schemaVersion_ = 1;
                onChanged();
                return this;
            }

            private java.lang.Object topic_ = "";
            /**
             * <code>optional string topic = 2;</code>
             * @return Whether the topic field is set.
             */
            public boolean hasTopic() {
                return ((bitField0_ & 0x00000002) != 0);
            }
            /**
             * <code>optional string topic = 2;</code>
             * @return The topic.
             */
            public java.lang.String getTopic() {
                java.lang.Object ref = topic_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        topic_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string topic = 2;</code>
             * @return The bytes for topic.
             */
            public com.google.protobuf.ByteString getTopicBytes() {
                java.lang.Object ref = topic_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    topic_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string topic = 2;</code>
             * @param value The topic to set.
             * @return This builder for chaining.
             */
            public Builder setTopic(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                topic_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }
            /**
             * <code>optional string topic = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearTopic() {
                topic_ = getDefaultInstance().getTopic();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }
            /**
             * <code>optional string topic = 2;</code>
             * @param value The bytes for topic to set.
             * @return This builder for chaining.
             */
            public Builder setTopicBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                topic_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>optional bytes payload = 3;</code>
             * @return Whether the payload field is set.
             */
            @java.lang.Override
            public boolean hasPayload() {
                return ((bitField0_ & 0x00000004) != 0);
            }
            /**
             * <code>optional bytes payload = 3;</code>
             * @return The payload.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getPayload() {
                return payload_;
            }
            /**
             * <code>optional bytes payload = 3;</code>
             * @param value The payload to set.
             * @return This builder for chaining.
             */
            public Builder setPayload(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                payload_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }
            /**
             * <code>optional bytes payload = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearPayload() {
                bitField0_ = (bitField0_ & ~0x00000004);
                payload_ = getDefaultInstance().getPayload();
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:proto.RawMessage)
        }

        // @@protoc_insertion_point(class_scope:proto.RawMessage)
        private static final fi.hsl.common.mqtt.proto.Mqtt.RawMessage DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new fi.hsl.common.mqtt.proto.Mqtt.RawMessage();
        }

        public static fi.hsl.common.mqtt.proto.Mqtt.RawMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<RawMessage> PARSER = new com.google.protobuf.AbstractParser<RawMessage>() {
            @java.lang.Override
            public RawMessage parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<RawMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RawMessage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public fi.hsl.common.mqtt.proto.Mqtt.RawMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_proto_RawMessage_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_proto_RawMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {"\n\nmqtt.proto\022\005proto\"F\n\nRawMessage\022\030\n\rSch"
                + "emaVersion\030\001 \002(\005:\0011\022\r\n\005topic\030\002 \001(\t\022\017\n\007pa"
                + "yload\030\003 \001(\014B \n\030fi.hsl.common.mqtt.protoB" + "\004Mqtt"};
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{});
        internal_static_proto_RawMessage_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_proto_RawMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_RawMessage_descriptor,
                new java.lang.String[]{"SchemaVersion", "Topic", "Payload",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
