name: Test and publish Maven package

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package -Dmaven.javadoc.skip=true -B -V
      - name: Run integration tests
        run: mvn failsafe:integration-test && mvn failsafe:verify
  publish:
    needs: test
    runs-on: ubuntu-latest
    # Run only for tagged commits
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete old versions of the package
        uses: actions/delete-package-versions@v4
        with:
          package-type: 'maven'
          package-name: 'fi.hsl.transitdata-common'
          min-versions-to-keep: 50
